apiVersion: v1
kind: Service
metadata:
  name: compute-interest-api
  labels:
    app: office-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office-space
    tier: compute
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compute-interest-api
  labels:
    app: office-space
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: office-space
        tier: compute
    spec:
      containers:
      - image: anthonyamanse/compute-interest-api:3.0
        imagePullPolicy: Always
        name: compute-interest-api
        env:
        - name: OFFICESPACE_MYSQL_DB_USER
          value: ''
        - name: OFFICESPACE_MYSQL_DB_PASSWORD
          value: ''
        - name: OFFICESPACE_MYSQL_DB_HOST
          value: ''
        - name: OFFICESPACE_MYSQL_DB_PORT
          value: ''
        - name: MYSQL_ENVIRONMENT
          value: ''
        ports:
        - containerPort: 8080
